# Generated by Django 4.0.5 on 2022-06-30 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='sum',
            new_name='price',
        ),
    ]
