# Generated by Django 4.0.5 on 2022-07-01 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_sum_bill_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='address',
            field=models.CharField(default=1, max_length=255, verbose_name='адрес'),
            preserve_default=False,
        ),
    ]
